# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- task: Maven@3
  inputs:
    mavenPomFile: 'my-app/pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'release:update-versions'

- task: Docker@2
  displayName: Build docker
  inputs:
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
    containerRegistry: 'docker-hub'
    repository: levka123/rafael
    tags: demo-azure

- script: |
    docker pull levka123/rafael:demo
    docker run levka123/rafael:demo bash -c "java -jar /opt/mycompany/app/my-app-1.0.*.jar"
    