# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master

pool:
  vmImage: ubuntu-latest


variables:
- name: artifact_tag
  value: error value 


steps:


- script: |
    sudo apt  install xmlstarlet
    fullname=$(cat my-app/pom.xml | sed -e 's/ xmlns.*=".*"//g' | xmlstarlet sel -t -v '//project/version')
    init_num=${fullname##*.*.}
    increm_num=$( expr $init_num + 1)
    prefix=${fullname%%$init_num}
    final_tag=$prefix$increm_num
    echo "##vso[task.setvariable variable=artifact_tag]$final_tag"
  displayName: Parse pom.xml and increment tag

#- task: Docker@2
#  displayName: Build docker
#  inputs:
#    command: 'buildAndPush'
#    Dockerfile: '**/Dockerfile_multistage'
#    containerRegistry: 'docker-hub'
#    repository: levka123/rafael
#    tags: $(artifact_tag)

- script: |
    docker build -f Dockerfile_multistage -t levka123/rafael:$(artifact_tag) --build-arg tag=$final_tag
    docker push levka123/rafael:$(artifact_tag)
  displayName: Build and push docker 

- script: |
    docker pull levka123/rafael:$(artifact_tag)
    docker run levka123/rafael:$(artifact_tag)
  displayName: Pull and run docker
