FROM maven:3.8.4-jdk-8 AS builder
#ARG tag=no_tag
WORKDIR /opt/mycompany/app/
COPY my-app .
#autoincrement can be used in case with NO input provided and no sync with docker tag required 
RUN mvn release:update-versions
RUN mvn package
#RUN mv -f target/my-app-*.jar target/my-app-$tag.jar

FROM openjdk:11-jdk
WORKDIR /opt/mycompany/app/
COPY --from=builder /opt/mycompany/app/target/my-app-*.jar .
RUN useradd lev
USER lev
CMD ["/bin/bash","-c","java -jar my-app-*.jar"]

